    # Keep X-Forwarded-Host if it exists, else use $host
map $http_x_forwarded_host $proxy_x_forwarded_host {
    default $http_x_forwarded_host;
    ""      $host;
}
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 10M;

    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    }

    location /oauth2/ {
        proxy_pass http://backend:8080/oauth2/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    }

    location /login/oauth2/ {
        proxy_pass http://backend:8080/login/oauth2/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    }

    location /logout {
        proxy_pass http://backend:8080/logout;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    }

    location /images/ {
        proxy_pass http://backend:8080/images/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $proxy_x_forwarded_host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}